In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%202/data/FuelConsumptionCo2.csv")

In [3]:
df.sample(5)

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
780,2014,MINI,COOPER CLUBMAN,SUBCOMPACT,1.6,4,A6,Z,8.7,6.6,7.8,36,179
406,2014,FORD,FOCUS FFV,COMPACT,2.0,4,M5,E,11.9,8.9,10.6,27,170
803,2014,MINI,COOPER S ROADSTER,TWO-SEATER,1.6,4,M6,Z,9.1,6.7,8.0,35,184
107,2014,BMW,650i xDRIVE COUPE,COMPACT,4.4,8,A8,Z,14.4,9.6,12.2,23,281
696,2014,MAZDA,CX-5,SUV - SMALL,2.5,4,AS6,X,9.6,7.4,8.6,33,198

In [4]:

df = df.drop(["MODELYEAR","MAKE","MODEL","VEHICLECLASS","TRANSMISSION","FUELTYPE"],axis=1)

In [5]:
df.sample(5)

,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
476,6.2,8,25.7,17.8,22.1,13,354
924,6.7,12,20.7,12.8,17.1,17,393
1006,4.6,8,16.9,12.8,15.1,19,347
876,3.4,6,12.4,8.6,10.7,26,246
811,1.6,4,9.1,6.7,8.0,35,184

In [6]:
df.corr()

,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
ENGINESIZE,1.000000,0.934011,0.832225,0.778746,0.819482,-0.808554,0.874154
CYLINDERS,0.934011,1.000000,0.796473,0.724594,0.776788,-0.770430,0.849685
FUELCONSUMPTION_CITY,0.832225,0.796473,1.000000,0.965718,0.995542,-0.935613,0.898039
FUELCONSUMPTION_HWY,0.778746,0.724594,0.965718,1.000000,0.985804,-0.893809,0.861748
FUELCONSUMPTION_COMB,0.819482,0.776788,0.995542,0.985804,1.000000,-0.927965,0.892129
FUELCONSUMPTION_COMB_MPG,-0.808554,-0.770430,-0.935613,-0.893809,-0.927965,1.000000,-0.906394
CO2EMISSIONS,0.874154,0.849685,0.898039,0.861748,0.892129,-0.906394,1.000000

In [17]:
df.head(3)

,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2.0,4,9.9,6.7,8.5,33,196
1,2.4,4,11.2,7.7,9.6,29,221
2,1.5,4,6.0,5.8,5.9,48,136

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067 entries, 0 to 1066
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ENGINESIZE                1067 non-null   float64
 1   CYLINDERS                 1067 non-null   int64
 2   FUELCONSUMPTION_CITY      1067 non-null   float64
 3   FUELCONSUMPTION_HWY       1067 non-null   float64
 4   FUELCONSUMPTION_COMB      1067 non-null   float64
 5   FUELCONSUMPTION_COMB_MPG  1067 non-null   int64
 6   CO2EMISSIONS              1067 non-null   int64
dtypes: float64(4), int64(3)
memory usage: 58.5 KB

In [ ]:
X = df.iloc[:,:-1]
y = df.iloc[:-1]

,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG
0,2.0,4,9.9,6.7,8.5,33
1,2.4,4,11.2,7.7,9.6,29
2,1.5,4,6.0,5.8,5.9,48
3,3.5,6,12.7,9.1,11.1,25
4,3.5,6,12.1,8.7,10.6,27
...,...,...,...,...,...,...
1062,3.0,6,13.4,9.8,11.8,24
1063,3.2,6,13.2,9.5,11.5,25
1064,3.0,6,13.4,9.8,11.8,24
1065,3.2,6,12.9,9.3,11.3,25
1066,3.2,6,14.9,10.2,12.8,22

In [29]:
from sklearn.model_selection import train_test_split
 
x_train,x_test,y_train,y_test = train_test_split(X,y,random_state=41,test_size=0.20)

ModuleNotFoundError: No module named 'sklearn'