In [98]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [115]:
df = pd.read_csv("D:\AI Engineering\Machine-Learning\Pakistani House Price Prediction\pakistan-housing-data.csv.csv")
df

<>:1: SyntaxWarning: invalid escape sequence '\A'
<>:1: SyntaxWarning: invalid escape sequence '\A'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_11476\3717918463.py:1: SyntaxWarning: invalid escape sequence '\A'
  df = pd.read_csv("D:\AI Engineering\Machine-Learning\Pakistani House Price Prediction\pakistan-housing-data.csv.csv")

,Location,Area,Baths,Beds,Dining Room,Laundry Room,Store Rooms,Kitchens,Drawing Room,Gym,Powder Room,Steam Room,No additional rooms,Prayer Rooms,Lounge or Sitting Room,Price
0,"Bahria Town, Lahore, Punjab",10 Marla,-,-,0,0,0,0,0,0,0,0,1,0,0,PKR3.5 Crore
1,"Al Rehman Garden, Lahore, Punjab",4 Marla,4,3,1,1,1,2,1,0,0,0,0,1,0,PKR1.32 Crore
2,"Central Park Housing Scheme, Lahore, Punjab",5 Marla,4,3,0,0,0,0,0,0,0,0,1,0,0,PKR1.74 Crore
3,"DHA Defence, Lahore, Punjab",1 Kanal,6,5,0,0,0,0,0,0,0,0,0,0,0,PKR10.3 Crore
4,"DHA Defence, Lahore, Punjab",1 Kanal,6,5,1,1,2,2,1,0,1,1,0,1,1,PKR8.25 Crore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,"Top City 1, Islamabad, Islamabad Capital",10 Marla,-,-,1,1,0,0,1,1,1,1,0,1,1,PKR4 Crore
7496,"Top City 1, Islamabad, Islamabad Capital",1 Kanal,-,-,1,1,0,0,1,1,1,1,0,1,1,PKR4.2 Crore
7497,"Top City 1, Islamabad, Islamabad Capital",10 Marla,-,-,1,1,0,0,1,1,1,1,0,1,1,PKR4 Crore
7498,"Mumtaz City, Islamabad, Islamabad Capital",6.7 Marla,-,-,1,1,0,0,1,1,1,1,0,1,1,PKR2.5 Crore
7499,"Top City 1, Islamabad, Islamabad Capital",10 Marla,-,-,1,1,0,0,1,1,1,1,0,1,1,PKR5 Crore

In [100]:
cols = ["Beds","Baths"]
for c in cols:
    df[c] = pd.to_numeric(df[c], errors="coerce")
df[cols] = df[cols].astype("Int64")

In [101]:
median_bath = df["Baths"].median()
median_beds = df["Beds"].median()

df["Baths"].fillna(median_bath, inplace=True)
df["Beds"].fillna(median_beds, inplace=True)

# Round to nearest whole number
df["Baths"] = df["Baths"].round().astype(int)
df["Beds"] = df["Beds"].round().astype(int)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11476\930019165.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Baths"].fillna(median_bath, inplace=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_11476\930019165.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Beds"].fillna(median_beds, inplace=True)

In [102]:
df[["Society", "City", "Province"]] = df["Location"].str.split(",", expand=True)
df[["Society", "City", "Province"]] = df[["Society", "City", "Province"]].apply(lambda col: col.str.strip())
df.drop(columns=["Location"], inplace=True)
df.head()

,Area,Baths,Beds,Dining Room,Laundry Room,Store Rooms,Kitchens,Drawing Room,Gym,Powder Room,Steam Room,No additional rooms,Prayer Rooms,Lounge or Sitting Room,Price,Society,City,Province
0,10 Marla,6,5,0,0,0,0,0,0,0,0,1,0,0,PKR3.5 Crore,Bahria Town,Lahore,Punjab
1,4 Marla,4,3,1,1,1,2,1,0,0,0,0,1,0,PKR1.32 Crore,Al Rehman Garden,Lahore,Punjab
2,5 Marla,4,3,0,0,0,0,0,0,0,0,1,0,0,PKR1.74 Crore,Central Park Housing Scheme,Lahore,Punjab
3,1 Kanal,6,5,0,0,0,0,0,0,0,0,0,0,0,PKR10.3 Crore,DHA Defence,Lahore,Punjab
4,1 Kanal,6,5,1,1,2,2,1,0,1,1,0,1,1,PKR8.25 Crore,DHA Defence,Lahore,Punjab

In [103]:
df.drop(columns=["Society"],inplace=True)

In [104]:
le_city = LabelEncoder()
df["City_encoded"] = le_city.fit_transform(df["City"])
df.drop(columns=["City"], inplace=True)
df.head()

,Area,Baths,Beds,Dining Room,Laundry Room,Store Rooms,Kitchens,Drawing Room,Gym,Powder Room,Steam Room,No additional rooms,Prayer Rooms,Lounge or Sitting Room,Price,Province,City_encoded
0,10 Marla,6,5,0,0,0,0,0,0,0,0,1,0,0,PKR3.5 Crore,Punjab,2
1,4 Marla,4,3,1,1,1,2,1,0,0,0,0,1,0,PKR1.32 Crore,Punjab,2
2,5 Marla,4,3,0,0,0,0,0,0,0,0,1,0,0,PKR1.74 Crore,Punjab,2
3,1 Kanal,6,5,0,0,0,0,0,0,0,0,0,0,0,PKR10.3 Crore,Punjab,2
4,1 Kanal,6,5,1,1,2,2,1,0,1,1,0,1,1,PKR8.25 Crore,Punjab,2

In [105]:
le_province = LabelEncoder()
df["Province_encoded"] = le_province.fit_transform(df["Province"])
df.drop(columns=["Province"], inplace=True)
df.head()

,Area,Baths,Beds,Dining Room,Laundry Room,Store Rooms,Kitchens,Drawing Room,Gym,Powder Room,Steam Room,No additional rooms,Prayer Rooms,Lounge or Sitting Room,Price,City_encoded,Province_encoded
0,10 Marla,6,5,0,0,0,0,0,0,0,0,1,0,0,PKR3.5 Crore,2,1
1,4 Marla,4,3,1,1,1,2,1,0,0,0,0,1,0,PKR1.32 Crore,2,1
2,5 Marla,4,3,0,0,0,0,0,0,0,0,1,0,0,PKR1.74 Crore,2,1
3,1 Kanal,6,5,0,0,0,0,0,0,0,0,0,0,0,PKR10.3 Crore,2,1
4,1 Kanal,6,5,1,1,2,2,1,0,1,1,0,1,1,PKR8.25 Crore,2,1

In [106]:
df["Area"] = df["Area"].str.strip()
df[["Area_Value", "Area_Unit"]] = df["Area"].str.split(" ", n=1, expand=True)
df.drop(columns=["Area"], inplace=True)
df.head()

,Baths,Beds,Dining Room,Laundry Room,Store Rooms,Kitchens,Drawing Room,Gym,Powder Room,Steam Room,No additional rooms,Prayer Rooms,Lounge or Sitting Room,Price,City_encoded,Province_encoded,Area_Value,Area_Unit
0,6,5,0,0,0,0,0,0,0,0,1,0,0,PKR3.5 Crore,2,1,10,Marla
1,4,3,1,1,1,2,1,0,0,0,0,1,0,PKR1.32 Crore,2,1,4,Marla
2,4,3,0,0,0,0,0,0,0,0,1,0,0,PKR1.74 Crore,2,1,5,Marla
3,6,5,0,0,0,0,0,0,0,0,0,0,0,PKR10.3 Crore,2,1,1,Kanal
4,6,5,1,1,2,2,1,0,1,1,0,1,1,PKR8.25 Crore,2,1,1,Kanal

In [107]:
df["Area_Value"] = df["Area_Value"].str.replace(",", "")
df["Area_Value"] = pd.to_numeric(df["Area_Value"])
df["Area_Value"].dtype

dtype('float64')

In [108]:
def convert_to_marla(row):
    if row["Area_Unit"] == "Kanal":
        return float(row["Area_Value"]) * 20        # 1 Kanal = 20 Marla
    elif row["Area_Unit"] == "Sq. Yd.":
        return float(row["Area_Value"]) / 25.2929   # 1 Marla = 25.2929 Sq. Yd.
    else:  # already Marla
        return float(row["Area_Value"])

df["Area_Marla"] = df.apply(convert_to_marla, axis=1)
df.drop(columns=["Area_Value", "Area_Unit"], inplace=True)
df.head()

,Baths,Beds,Dining Room,Laundry Room,Store Rooms,Kitchens,Drawing Room,Gym,Powder Room,Steam Room,No additional rooms,Prayer Rooms,Lounge or Sitting Room,Price,City_encoded,Province_encoded,Area_Marla
0,6,5,0,0,0,0,0,0,0,0,1,0,0,PKR3.5 Crore,2,1,10.0
1,4,3,1,1,1,2,1,0,0,0,0,1,0,PKR1.32 Crore,2,1,4.0
2,4,3,0,0,0,0,0,0,0,0,1,0,0,PKR1.74 Crore,2,1,5.0
3,6,5,0,0,0,0,0,0,0,0,0,0,0,PKR10.3 Crore,2,1,20.0
4,6,5,1,1,2,2,1,0,1,1,0,1,1,PKR8.25 Crore,2,1,20.0

In [109]:
new_cols = ["City_encoded", "Province_encoded", "Area_Marla"]
remaining = [col for col in df.columns if col not in new_cols]
df = df[new_cols + remaining]
df.head()

,City_encoded,Province_encoded,Area_Marla,Baths,Beds,Dining Room,Laundry Room,Store Rooms,Kitchens,Drawing Room,Gym,Powder Room,Steam Room,No additional rooms,Prayer Rooms,Lounge or Sitting Room,Price
0,2,1,10.0,6,5,0,0,0,0,0,0,0,0,1,0,0,PKR3.5 Crore
1,2,1,4.0,4,3,1,1,1,2,1,0,0,0,0,1,0,PKR1.32 Crore
2,2,1,5.0,4,3,0,0,0,0,0,0,0,0,1,0,0,PKR1.74 Crore
3,2,1,20.0,6,5,0,0,0,0,0,0,0,0,0,0,0,PKR10.3 Crore
4,2,1,20.0,6,5,1,1,2,2,1,0,1,1,0,1,1,PKR8.25 Crore

In [110]:
def convert_to_crore(val):
    val = val.strip().replace("PKR", "").strip()
    if "Crore" in val:
        return float(val.replace("Crore", "").strip())
    elif "Lakh" in val:
        return float(val.replace("Lakh", "").strip()) / 100  # 1 Crore = 100 Lakh
    
df["Price"] = df["Price"].apply(convert_to_crore)
df["Price"].dtype

dtype('float64')

In [111]:

df["Price"].fillna(df["Price"].median(), inplace=True)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11476\364657401.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Price"].fillna(df["Price"].median(), inplace=True)

In [112]:
df

,City_encoded,Province_encoded,Area_Marla,Baths,Beds,Dining Room,Laundry Room,Store Rooms,Kitchens,Drawing Room,Gym,Powder Room,Steam Room,No additional rooms,Prayer Rooms,Lounge or Sitting Room,Price
0,2,1,10.0,6,5,0,0,0,0,0,0,0,0,1,0,0,3.50
1,2,1,4.0,4,3,1,1,1,2,1,0,0,0,0,1,0,1.32
2,2,1,5.0,4,3,0,0,0,0,0,0,0,0,1,0,0,1.74
3,2,1,20.0,6,5,0,0,0,0,0,0,0,0,0,0,0,10.30
4,2,1,20.0,6,5,1,1,2,2,1,0,1,1,0,1,1,8.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,0,0,10.0,6,5,1,1,0,0,1,1,1,1,0,1,1,4.00
7496,0,0,20.0,6,5,1,1,0,0,1,1,1,1,0,1,1,4.20
7497,0,0,10.0,6,5,1,1,0,0,1,1,1,1,0,1,1,4.00
7498,0,0,6.7,6,5,1,1,0,0,1,1,1,1,0,1,1,2.50
7499,0,0,10.0,6,5,1,1,0,0,1,1,1,1,0,1,1,5.00

In [114]:
df.corr()

,City_encoded,Province_encoded,Area_Marla,Baths,Beds,Dining Room,Laundry Room,Store Rooms,Kitchens,Drawing Room,Gym,Powder Room,Steam Room,No additional rooms,Prayer Rooms,Lounge or Sitting Room,Price
City_encoded,1.000000,0.500000,-0.090733,-0.122449,-0.278790,0.028307,-0.031087,0.066035,0.106736,0.045813,-0.025066,0.091126,0.002057,0.012399,0.041444,0.005250,-0.214183
Province_encoded,0.500000,1.000000,-0.055526,-0.207083,-0.194537,-0.066724,-0.160346,-0.048728,-0.130260,-0.076926,-0.082305,-0.112356,-0.161470,0.041899,-0.113392,-0.105986,-0.135992
Area_Marla,-0.090733,-0.055526,1.000000,0.380245,0.454023,0.114823,0.146028,0.186514,0.117560,0.087048,0.127446,0.144863,0.160964,-0.092656,0.151141,0.124545,0.664404
Baths,-0.122449,-0.207083,0.380245,1.000000,0.758308,0.163697,0.189443,0.172291,0.225148,0.127445,0.138687,0.186555,0.199603,-0.116847,0.172409,0.153615,0.360546
Beds,-0.278790,-0.194537,0.454023,0.758308,1.000000,0.107984,0.138272,0.173682,0.209023,0.077334,0.110821,0.106010,0.147043,-0.084148,0.116690,0.109326,0.441732
Dining Room,0.028307,-0.066724,0.114823,0.163697,0.107984,1.000000,0.667069,0.326157,0.554512,0.898015,0.445559,0.691806,0.549015,-0.597092,0.628253,0.727262,0.112673
Laundry Room,-0.031087,-0.160346,0.146028,0.189443,0.138272,0.667069,1.000000,0.351614,0.431290,0.655669,0.560355,0.714098,0.717101,-0.436162,0.708943,0.777563,0.159431
Store Rooms,0.066035,-0.048728,0.186514,0.172291,0.173682,0.326157,0.351614,1.000000,0.480899,0.334887,0.236559,0.339996,0.303643,-0.310206,0.324368,0.346510,0.152579
Kitchens,0.106736,-0.130260,0.117560,0.225148,0.209023,0.554512,0.431290,0.480899,1.000000,0.584239,0.228494,0.464404,0.319908,-0.528314,0.368914,0.501237,0.103166
Drawing Room,0.045813,-0.076926,0.087048,0.127445,0.077334,0.898015,0.655669,0.334887,0.584239,1.000000,0.419819,0.703274,0.519859,-0.629756,0.595131,0.744894,0.089373
Gym,-0.025066,-0.082305,0.127446,0.138687,0.110821,0.445559,0.560355,0.236559,0.228494,0.419819,1.000000,0.557351,0.718544,-0.272439,0.665448,0.500105,0.168355
Powder Room,0.091126,-0.112356,0.144863,0.186555,0.106010,0.691806,0.714098,0.339996,0.464404,0.703274,0.557351,1.000000,0.667959,-0.469263,0.733376,0.711132,0.143107
Steam Room,0.002057,-0.161470,0.160964,0.199603,0.147043,0.549015,0.717101,0.303643,0.319908,0.519859,0.718544,0.667959,1.000000,-0.339195,0.784180,0.618715,0.164197
No additional rooms,0.012399,0.041899,-0.092656,-0.116847,-0.084148,-0.597092,-0.436162,-0.310206,-0.528314,-0.629756,-0.272439,-0.469263,-0.339195,1.000000,-0.390135,-0.511491,-0.093276
Prayer Rooms,0.041444,-0.113392,0.151141,0.172409,0.116690,0.628253,0.708943,0.324368,0.368914,0.595131,0.665448,0.733376,0.784180,-0.390135,1.000000,0.619678,0.142611
Lounge or Sitting Room,0.005250,-0.105986,0.124545,0.153615,0.109326,0.727262,0.777563,0.346510,0.501237,0.744894,0.500105,0.711132,0.618715,-0.511491,0.619678,1.000000,0.137777
Price,-0.214183,-0.135992,0.664404,0.360546,0.441732,0.112673,0.159431,0.152579,0.103166,0.089373,0.168355,0.143107,0.164197,-0.093276,0.142611,0.137777,1.000000